### ISSUE TITLE
'ng-lottie' is not a known element: 1. If 'ng-lottie' is an Angular component, then verify that it is part of this module.

### ISSUE THREAD

**Issue by iqbalgithub1998** [ngx-lottie/ngx-lottie#109]
I follow all steps in the documentation but still I m getting an error "'ng-lottie' is not a known element:
1. If 'ng-lottie' is an Angular component, then verify that it is part of this module." i don't know why 
2. these are my dependancies "@angular/common": "~12.0.1",
    "@angular/core": "~12.0.1",
    "@angular/forms": "~12.0.1",
    "@angular/platform-browser": "~12.0.1",
    "@angular/platform-browser-dynamic": "~12.0.1",
    "@angular/router": "~12.0.1",
    "@capacitor/android": "^3.0.2",
    "@capacitor/app": "1.0.2",
    "@capacitor/clipboard": "^1.0.2",
    "@capacitor/core": "3.0.2",
    "@capacitor/haptics": "1.0.2",
    "@capacitor/keyboard": "1.0.2",
    "@ionic-native/clipboard": "^5.34.0",
    "@ionic/angular": "^5.5.2",
    "@ionic/storage-angular": "^3.0.6",
    "cordova-android": "9.1.0",
    "cordova-clipboard": "^1.3.0",
    "lottie-web": "^5.7.11",
    "ng-lottie": "^0.3.2",
    "ngx-lottie": "^7.0.3",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"

**Comment by arturovt** [comment]
You're mixing 2 libraries `ng-lottie` and `ngx-lottie` which are unrelated. Please, provide a minimal reproducible example. Feel free to re-open when it exists.
