### ISSUE TITLE
Cache causing performance issues

### ISSUE THREAD

**Issue by CyrilGC** [ngx-lottie/ngx-lottie#115]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have about 10 different lottie files displayed on my home page. If I activate the cache (with LottieCacheModule.forRoot()), and navigate to a different page (via the router) and back to the home page, I get performance issues. The animations are not smoothed anymore. It gets worse each time I navigate back to the home page. After 3 or 4 times, the page becomes completely unresponsive.
If I deactivate the cache, I don't have any performance issues.

## Environment

<pre><code>
Libs:
- @angular/core version: 12.0.4
- ngx-lottie version: 7.0.3

Browser:
- [x ] Chrome (desktop) version 93.0.4577.82
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.16.1  
- Platform:  Windows

**Comment by arturovt** [comment]
Hey, I cannot say what might be causing your issue until you provide a minimal reproducible example.

**Comment by zwjohn** [comment]
I am running into the same issue, the page freezes if loading page with lottie files multiple times with cache enabled. Removing the LottieCacheModule.forRoot() solves the issue. There is definitely there is issue with caching

**Comment by CyrilGC** [comment]
I will try to get an example ready tomorrow

**Comment by zwjohn** [comment]
This is likely caused by the animationData not deep cloned. It seems to be a known issue for lottie.js since the cached animationData mutated and reusing the cached animationData object could cause issues.

Here is the statement from lottie-web
animationData: an Object with the exported animation data. Note: If your animation contains repeaters and you plan to call loadAnimation multiple times with the same animation, please deep clone the object before passing it (see #1159 and #2151.)

**Comment by CyrilGC** [comment]
[lottie-cache-test.zip](https://github.com/ngx-lottie/ngx-lottie/files/7227756/lottie-cache-test.zip)
Here is an example that shows the issue.

**Comment by arturovt** [comment]
> This is likely caused by the animationData not deep cloned. It seems to be a known issue for lottie.js since the cached animationData mutated and reusing the cached animationData object could cause issues.
> 
> Here is the statement from lottie-web
> animationData: an Object with the exported animation data. Note: If your animation contains repeaters and you plan to call loadAnimation multiple times with the same animation, please deep clone the object before passing it (see #1159 and #2151.)

Considering the statement above, could you try to debug the code locally by updating node_modules? There is a class called `CacheableAnimationLoader`, it has a `transformOptions` method which removes the path property and gets an animation data from the cache. You can add a deep clone function there and pass that animation data.

I’m onto phone next days so can’t promise that I’ll check it on weekends.

**Comment by CyrilGC** [comment]
Doing a deep copy seems to fix the issue.

**Comment by arturovt** [comment]
Ok, I can add a deep clone function further and publish a beta version to give you a try, I’ll just use the deepClone from the lodash-es. I’ll also need to reproduce the issue locally using your example to confirm the fix.

**Comment by zwjohn** [comment]
@arturovt  it may not be worth it to import lodash library just for it's clone function. I used  JSON.stringify and JSON.parse to dereference the object, and it worked. see below
   
```
awaitConfigAndCache(options, animationItem) {
        if (this.isAnimationConfigWithPath(options)) {
            // Don't wait for the `config_ready` event if it has been cached previously.
            if (this.cache.has(options.path)) {
                return;
            }
            animationItem.addEventListener('config_ready', () => {
                this.cache.set(options.path, JSON.stringify(animationItem['animationData']));
            });
        }
    }
    transformOptions(options) {
        if (this.isAnimationConfigWithPath(options) && this.cache.has(options.path)) {
            return Object.assign(Object.assign({}, options), { path: undefined, animationData: JSON.parse(this.cache.get(options.path)) });
        }
        else {
            return options;
        }
    }
```

**Comment by arturovt** [comment]
Alright, I was thinking that `animationData` might be mutated with some extra properties that cannot be cloned (e.g. functions, symbols, etc.).

**Comment by arturovt** [comment]
I've published the `ngx-lottie@7.0.4-beta`.

**Comment by zwjohn** [comment]
@arturovt great! Tested working.
I was wondering if you could expose the cache Map object or clear() method of the map, so that I can manually clear the cache when the cache is not needed anymore, otherwise, the cache stays in memory even when the application doesn't use the cache anymore. 
thanks!

**Comment by arturovt** [comment]
I've published the `ngx-lottie@7.0.4` and exposed the `AnimationLoader` class. You can inject it and get the cache property through this hack (since the cacheable loader is not public and not injectable):
```ts
constructor(animationLoader: AnimationLoader) {
  animationLoader['cache'].clear() // clear the cache somewhere when the application doesn't use it
}
```

**Comment by zwjohn** [comment]
@arturovt perfect, thanks!

**Comment by CyrilGC** [comment]
Thanks @arturovt . I just tested the 7.0.4 and it is working great.
