### ISSUE TITLE
Question: How to bind animation with scrolling 

### ISSUE THREAD

**Issue by me-dira** [ngx-lottie/ngx-lottie#125]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[x] Other... Please describe:
</code></pre>

## What is the motivation / use case for changing the behavior?

Hey,
I want to implement some kind of animation that interacts to user scrolling and plays an smooth animation when user
is going all down to the website.
In the outer world of angular you can do this with Lottie interactivity package and its working very good but, the problem is that my project implemented by angular and I just tried everything ( everything i was able to try ) and you know, technically I'm junior in angular development.

Is there any hope that I can do this in the future? 

## Environment

<pre><code>
Libs:
- @angular/core version: X.Y.Z
- ngx-lottie version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v16.10.0  
- Platform: Linux  

Others:

</code></pre>

**Comment by arturovt** [comment]
@tomer953 I don't have any experience with `lottie-interactivity` library, but I have to take a look what it's doing and what it requires to work.

I don't think I'm able to implement the same functionality in this library, I can only try to provide an integration with already existing solution.

This is not the first request related to the lottie interactivity. I don't promise any ETA, and also I cannot say if I'll find an approach to integrate with it or not. I'll keep updated.

**Comment by tomer953** [comment]
Hi,

thanks. I just discovered Lottie today. 
so I also saw the interactive tutorial in the official websites and wondered if its supported in angular:
https://lottiefiles.com/interactivity
Actually at this point I just explore, but i can see why the scroll binding could be helpful and cool. 
So if you could achieve the same with pure rxjs or the existing events, please share!
