### ISSUE TITLE
No provider for AnimationLoader!

### ISSUE THREAD

**Issue by touchpoll** [ngx-lottie/ngx-lottie#126]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am using angular material dialog. I tried to  show lazy loaded dialog, inside which the ng-lottie component is located and I've got an error "No provider for AnimationLoader!"

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ivy-yakhbc?
click on show dialog

## Environment

<pre><code>
Libs:
- @angular/core version: ~13.1.0
- ngx-lottie version: 8.0.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [x ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  
Mac

Others:

</code></pre>

**Comment by arturovt** [comment]
You haven’t imported the Lottie module into the root module.

**Comment by touchpoll** [comment]
I don't need to import this in the root module.  I import Lottie module in lazy loaded module.

can't I use lotti module as part of lazy loading module ? or should i import it only in root module ?
