### ISSUE TITLE
lottie-web-build-player-lottie_svg.js should be loaded only when animation gets rendered for the first time

### ISSUE THREAD

**Issue by yairweiss1** [ngx-lottie/ngx-lottie#127]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`lottie-web-build-player-lottie_svg.js` is loaded on startup even though I used dynamic import with Webpack magic comments as described: "The lottie-web library can be loaded on demand using dynamic import. Webpack will load this library only when your animation gets rendered for the first time"

## Expected behavior
`lottie-web-build-player-lottie_svg.js` should be loaded only when animation gets rendered for the first time

## Minimal reproduction of the problem with instructions
I did as described in the "Usage" section (and excluded CanvasRenderer and HybridRenderer as described in "Reducing lottie-web bundle size" section:
```js
import { NgModule } from '@angular/core';
import { LottieModule } from 'ngx-lottie';

export function playerFactory() {
  return import(/* webpackChunkName: 'lottie-web' */ 'lottie-web/build/player/lottie_svg');
}

@NgModule({
  imports: [LottieModule.forRoot({ player: playerFactory })],
})
export class AppModule {}
```
## Environment

<pre><code>
Libs:
- @angular/core version: 11.2.14
- ngx-lottie version: 6.4.0

Browser:
- [x] Chrome (desktop) version 98
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12
- Platform:  Windows

</code></pre>

**Comment by arturovt** [comment]
Can you provide a minimal reproducible example? Because I tried that locally and it works as expected for me, the JS file is not loaded until the first animation is rendered.

**Comment by yairweiss1** [comment]
Sorry, my mistake. I found one place in our code that uses `ng-lottie` even though the component is not shown to the user, that's why it wasn't lazy-loaded. I fixed it and it work as expected. Thanks
