### ISSUE TITLE
Upgrading to latest lottie-web, introduces a runtime error

### ISSUE THREAD

**Issue by masimplo** [ngx-lottie/ngx-lottie#130]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Using the latest version of Lottie-Web 5.9.2 produces a runtime error related to types:

```
Error: node_modules/ngx-lottie/lib/symbols.d.ts:60:47 - error TS2314: Generic type 'AnimationConfigWithData' requires 1 type argument(s).

60 export declare type AnimationConfigWithData = import('lottie-web').AnimationConfigWithData;
```

They have converted that type to a generic type in version 5.9.x from what I can tell.

## Expected behavior

ngx-lottie should be compatible with latest lottie-web

## Minimal reproduction of the problem with instructions

Install latest ngx-lottie and latest Lottie-web on any sample and try to run it.

## Environment

<pre><code>
Libs:
- @angular/core version:  "13.3.0",
- ngx-lottie version: "8.0.1"
- lottie-web version: 5.9.2
- "typescript": "4.5.4",

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   16.14.2
- Platform:  Mac

Others:

</code></pre>

**Comment by jackz7** [comment]
Now, build is not working with it's previous version on my system

**Comment by jackz7** [comment]
If anyone is not strictly limited to use `ngx-lottie` then you can try 

https://stackoverflow.com/a/60971710/10763750

It is working for me :)

**Comment by arturovt** [comment]
I've published `8.1.0` with a fix, it now requires `5.9.2` as a minimum `lottie-web` version. Unfortunately, they're introducing breaking changes unsafely in patch bumps, the breaking change has been shipped in `5.9.2` with this commit: https://github.com/airbnb/lottie-web/commit/cc2d4f333884f847a30036b873695e782b9f22a8.

**Comment by julianwilkinson** [comment]
@arturovt thanks for doing this. Will 7.x be fixed as well?

**Comment by klipnot** [comment]
> @arturovt thanks for doing this. Will 7.x be fixed as well?
I hope it will 🤞

**Comment by arturovt** [comment]
> @arturovt thanks for doing this. Will 7.x be fixed as well?

`ngx-lottie@7.1.0`.
