### ISSUE TITLE
How to update lottie without reseting the frame?

### ISSUE THREAD

**Issue by Rathero** [ngx-lottie/ngx-lottie#136]
Hello, 
I'm using this awesome package for one website i'm working on. We want to allow the users to update some values from the lottie file (like image, texts, colors, etc.)
For that, we updating the animationData object and then send it back to the library like this:

this.options = {
      ...this.options, 
      animationData: this.animationData //We update this animation data with the proper new values.
    };

The thing is, if we do this way, animation is reset. So in case it was already playing and, for example, in frame number 60, it resets to frame 0, and we want it to keep playing where it was.

Is it possible somehow?

Thanks!

PD: You can find out example of our application here: https://animm-ui.web.app/animation/1 and you'll see the issue.

**Comment by arturovt** [comment]
Hey, I’ve thought about this one when I was implementing the animation update. Unfortunately, Lottie-web doesn’t provide this functionality natively, this is the comment from their core developer:
> hi, if you want to change an animation, I suggest that you destroy the previous one and load a new one instead
