### ISSUE TITLE
Missing property on BMCompleteLoopEvent

### ISSUE THREAD

**Issue by TrueRihot** [ngx-lottie/ngx-lottie#138]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

While subscribing to the loop event on a lottieplayer, an error is thrown because the property "currentLoop" is missing on BMCompleteLoopEvent. Hence we have to manually extend the type in our ts.

## Expected behavior

"currenLoop" should be provided by default in BMCompleteLoopEvent.

## What is the motivation / use case for changing the behavior?

I want to stop the animation after a certain amount of loops.

## Environment

<pre><code>
Libs:
- @angular/core version: 12.2.16
- ngx-lottie version: 7.0.4
- 

Browser:
- [X ] Chrome (desktop) version XX
- [ X] Chrome (Android) version XX
- [ X] Chrome (iOS) version XX
- [ X] Firefox version XX
- [ X] Safari (desktop) version XX
- [ X] Safari (iOS) version XX
- [ X] IE version XX
- [ X] Edge version XX
 
For Tooling issues:
- Node version: 18.0.0  
- Platform: Mac 

Others:

</code></pre>

**Comment by arturovt** [comment]
`ngx-lottie@8.2.1`.
