### ISSUE TITLE
The version 8.2.1 is not compatible with angular 13

### ISSUE THREAD

**Issue by alx1417** [ngx-lottie/ngx-lottie#141]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
On install the last version "8.2.1" tha application crashes on start with angular 13, because seams that the library has been compiled with angualr 14.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/12087126/183613797-66dbf864-a291-4619-ae22-9ca887e47484.png)

## Expected behavior

Version 8.2.1 should work with angular 13.

## Minimal reproduction of the problem with instructions

* Step 1: Create a project with angualr 13
* Step 2: Install ngx-lottie library version 8.2.1
* Step 3: Add a small example.
* Step 4: Start the project.

## Environment

<pre><code>
Libs:
- @angular/core version: 13.3.11
- ngx-lottie version: 8.2.1

For Tooling issues:
- Node version: 16.14.2
- Platform:  Mac

</code></pre>

**Comment by Zryru** [comment]
@arturovt It would seem the latest release has some issues, pinging you since it says you released it.

**Comment by mgecmez** [comment]
![image](https://user-images.githubusercontent.com/16095729/183639932-db5adb59-6d56-43fc-b89c-d5271df2e4e0.png)

I guess I have a similar problem.

**Comment by findela** [comment]
Same problem, the only way it seems to fix this -  Downgrading package version to **V7**

**Comment by arturovt** [comment]
Hey, this seems like there might be breaking change in ng-packagr. The `8.2.0` version has been built with `ng-packagr@14.0.2` (which is Angular 14 basically), but no one has reported any issues. I'll have a look on these weekends.

**Comment by alx1417** [comment]
@arturovt As you say, with version 8.2.0 it works correctly, I have fixed it to this version.

**Comment by arturovt** [comment]
I've reverted Angular 14 change and publish 8.2.2.

**Comment by arturovt** [comment]
Closing as resolved.
