### ISSUE TITLE
Export internally used InjectionKeys and Classes

### ISSUE THREAD

**Issue by iCrawl** [ngx-lottie/ngx-lottie#146]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently it is pretty much impossible to use this library in standalone components introduced in Angular 14: https://angular.io/guide/standalone-components

## Expected behavior

Solving this would simply involve exporting a few things that are currently not exported in the library to avoid having to call `.forRoot()` to setup providers and let us users set those providers manually, as standalone components require us to.

Namely:
- `LOTTIE_OPTIONS` InjectionToken
- `CacheableAnimationLoader`

This way we can set it up like this:

```ts
export async function lottiePlayerFactory() {
  return import(/* webpackChunkName: 'lottie-web' */ 'lottie-web');
}

@Component({
  selector: 'eo-lottie-animation',
  standalone: true,
  imports: [LottieModule, AsyncPipe],
  providers: [AnimationLoader, { provide: LOTTIE_OPTIONS, useValue: { useWebWorker: true, player: lottiePlayerFactory } }],
  template: '<ng-lottie [options]="options$ | async" (animationCreated)="animationCreated($event)"></ng-lottie>',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LottieAnimationComponent {
  @Input()
  public set animation(name: string) {
    this._options$.next({ path: `/assets/animations/${name}.json` });
  }

  private readonly _options$ = new BehaviorSubject<AnimationOptions>({
    path: '/assets/animations/white-loading.json',
  });

  public readonly options$ = this._options$.asObservable();

  public animationCreated(animationItem: AnimationItem): void {
    console.log(animationItem);
  }
}
```

## What is the motivation / use case for changing the behavior?

Ability to use this library in standalone components in Angular 14.

## Environment

<pre><code>
Libs:
- @angular/core version: ^14.2.0
- ngx-lottie version: ^9.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 104.0.1293.70 (Official build) (arm64)
 
For Tooling issues:
- Node version: 16.16.0
- Platform: macOS

**Comment by arturovt** [comment]
Yeah that makes sense, I think I will export functions like Angular does, e.g. `provideAnimationLoader()`, `provideLottieOptions()`.

**Comment by arturovt** [comment]
@iCrawl https://github.com/ngx-lottie/ngx-lottie/pull/149
