### ISSUE TITLE
unable to install lottie packages

### ISSUE THREAD

**Issue by nicolgit** [ngx-lottie/ngx-lottie#147]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am executing the following command

` npm i lottie-web ngx-lottie`

## Expected behavior
Lottie module installed

## Minimal reproduction of the problem with instructions
` npm i lottie-web ngx-lottie`

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: firewall-mon-app@0.0.0
npm ERR! Found: @angular/core@12.2.16
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~12.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@">=14" from ngx-lottie@9.0.1
npm ERR! node_modules/ngx-lottie
npm ERR!   ngx-lottie@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\....txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\....log
```

## What is the motivation / use case for changing the behavior?
N/A

## Environment

<pre><code>
```
Libs:
Angular CLI: 12.2.18
Node: 16.17.0 (Unsupported)
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 12.2.16
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.18
@angular-devkit/build-angular   12.2.18
@angular-devkit/core            12.2.18
@angular-devkit/schematics      12.2.18
@angular/cdk                    12.2.13
@angular/cli                    12.2.18
@angular/material               12.2.13
@schematics/angular             12.2.18
rxjs                            6.6.7
typescript                      4.3.5
```

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Windows

Others:
</code></pre>

**Comment by arturovt** [comment]
There’s a compatibility table with Angular versions at the top of the readme.
