### ISSUE TITLE
App crashed by TypeError: Cannot add property 0, object is not extensible

### ISSUE THREAD

**Issue by alunenko** [ngx-lottie/ngx-lottie#155]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The app crashing during run time

## Expected behavior
The app lunch without errors

## Minimal reproduction of the problem with instructions
* Template: ```<ng-lottie [options]="lottieConfig" (complete)="complete($event)"></ng-lottie>```
* the *.ts file
<pre><code>constructor(...) {
    this.lottieConfig = {
      path: 'assets/animations/lottie-winner.json',
      autoplay: true,
      initialSegment: [0, 75]
    };
}

complete(e: any): void {
  NgZone.assertInAngularZone();
  console.log('completed');
}
</code></pre>
* The app will crash during run time with console error
<pre><code>
angular.min.js:127 TypeError: Cannot add property 0, object is not extensible
    at TCleanup.push (<anonymous>)
    at listenerInternal (core.mjs:15940:34)
    at Module.ɵɵlistener (core.mjs:15818:5)
    at BattleWinnerComponent_Template (winner.component.html:33:18)
    at executeTemplate (core.mjs:12190:9)
    at renderView (core.mjs:12012:13)
    at renderComponent (core.mjs:13257:5)
    at renderChildComponents (core.mjs:11871:9)
    at renderView (core.mjs:12037:13)
    at renderComponent (core.mjs:13257:5) '<app-active-container _nghost-vup-c85="" ng-version="15.0.0">'
</code></pre>

## What is the motivation / use case for changing the behavior?
The app will crash during run time with console error.

## Environment

<pre><code>
Libs:
- @angular/core version: 15.0.0
- ngx-lottie version: 10.0.0

Browser:
- [X] Chrome (desktop) version 107.0.5304.110
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v16.16.0
- Platform:  macOS Ventura Version 13.0

Others:
_
</code></pre>

**Comment by arturovt** [comment]
Could you provide a minimal reproducible example?

**Comment by alunenko** [comment]
@arturovt good point.
Issue isn't related to here. I was not patient. The issue is in my app.
