### ISSUE TITLE
Switching between animations causes reload

### ISSUE THREAD

**Issue by kimo-do** [ngx-lottie/ngx-lottie#159]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Right now when I have an object that consists of multiple separate animation .json files. Every time I load the second animation, there is a noticable refresh of the component.

## Expected behavior

What I'm looking for is for the animation to continue with it's next animation seamlessly without any skipped frames. Is it possible to preload the animations so you can transition between them instantly?

## Minimal reproduction of the problem with instructions

* Show animation with path = animation01.json
* Change path to animation02.json
* See how they flash not making them transition seamlessly

## Environment

<pre><code>
Libs:
- @angular/core version: Latest
- ngx-lottie version: Latest

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: V18.12.0  
- Platform:  Windows

Others:

</code></pre>

**Comment by arturovt** [comment]
This library is basically a proxy to the core library called Lottie-web. I haven’t heard they added any functionality to switching animations without flush.
