### ISSUE TITLE
Upgrade to Angular v16

### ISSUE THREAD

**Issue by Zarkos69** [ngx-lottie/ngx-lottie#164]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Are there any plans on upgrading to Angular v16? 

## What is the motivation / use case for changing the behavior?
Compatibility with Angular v16? :)

**Comment by arturovt** [comment]
Is this not compatible with 16 version?

**Comment by Zarkos69** [comment]
mmmm, Since the update I get the following Error message:

`NullInjectorError: R3InjectorError(Standalone[StorybookWrapperComponent])[AnimationLoader -> AnimationLoader -> InjectionToken LottieOptions -> InjectionToken LottieOptions]: 
  NullInjectorError: No provider for InjectionToken LottieOptions!
    at NullInjector.get (core.mjs:8760:1)
    at R3Injector.get (core.mjs:9189:1)
    at R3Injector.get (core.mjs:9189:1)
    at injectInjectorOnly (core.mjs:651:1)
    at Module.ɵɵinject (core.mjs:655:1)
    at Object.AnimationLoader_Factory [as factory] (ngx-lottie.mjs:40:1)
    at R3Injector.hydrate (core.mjs:9290:1)
    at R3Injector.get (core.mjs:9178:1)
    at R3Injector.get (core.mjs:9189:1)
    at ChainedInjector.get (core.mjs:12995:1)`
    
    We have not changed the way we implement Lottie (So still through `[LottieModule.forRoot({ player: playerFactory })]`
    Also looked at the changes from angular 15 -> 16
    
    These are de dependencies:
    `"dependencies": {
    "@angular/animations": "16.1.1",
    "@angular/common": "16.1.1",
    "@angular/compiler": "16.1.1",
    "@angular/core": "16.1.1",
    "@angular/forms": "16.1.1",
    "@angular/platform-browser": "16.1.1",
    "@angular/platform-browser-dynamic": "16.1.1",
    "@angular/router": "16.1.1",
    "@fortawesome/fontawesome-free": "^6.4.0",
    "@ngneat/until-destroy": "^9.2.3",
    "@types/uuid": "^9.0.2",
    "dayjs": "^1.11.8",
    "ng-zorro-antd": "^16.0.0",
    "ngx-lottie": "^10.0.0",
    "ngx-pipes": "^3.2.2",
    "rxjs": "7.8.1",
    "tslib": "^2.5.3",
    "uuid": "^9.0.0",
    "zone.js": "0.13.1",
    "@nx/angular": "16.3.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "16.1.0",
    "@angular-devkit/core": "16.1.0",
    "@angular-devkit/schematics": "16.1.0",
    "@angular-eslint/eslint-plugin": "16.0.3",
    "@angular-eslint/eslint-plugin-template": "16.0.3",
    "@angular-eslint/template-parser": "16.0.3",
    "@angular/cli": "~16.1.0",
    "@angular/compiler-cli": "16.1.1",
    "@angular/language-service": "16.1.1",
    "@nx/cypress": "16.3.2",
    "@nx/eslint-plugin": "16.3.2",
    "@nx/jest": "16.3.2",
    "@nx/linter": "16.3.2",
    "@nx/storybook": "16.3.2",
    "@nx/workspace": "16.3.2",
    "@schematics/angular": "16.1.0",
    "@storybook/addon-essentials": "7.0.21",
    "@storybook/angular": "7.0.21",
    "@storybook/core-server": "7.0.21",
    "@types/jest": "29.5.2",
    "@types/node": "20.3.1",
    "@typescript-eslint/eslint-plugin": "5.59.11",
    "@typescript-eslint/parser": "5.59.11",
    "cypress": "^12.14.0",
    "eslint": "~8.42.0",
    "eslint-config-prettier": "8.8.0",
    "eslint-plugin-cypress": "^2.13.3",
    "eslint-plugin-storybook": "^0.6.12",
    "eslint-plugin-wds": "file:libs/eslint-custom-wds",
    "husky": "^8.0.3",
    "jest": "29.5.0",
    "jest-environment-jsdom": "29.5.0",
    "jest-junit": "^16.0.0",
    "jest-preset-angular": "13.1.1",
    "jest-sonar-reporter": "^2.0.0",
    "ng-packagr": "16.1.0",
    "nx": "16.3.2",
    "postcss": "^8.4.24",
    "postcss-import": "~15.1.0",
    "postcss-preset-env": "~8.5.0",
    "postcss-url": "~10.1.3",
    "prettier": "^2.8.8",
    "pretty-quick": "^3.1.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "storybook": "^7.0.21",
    "storybook-addon-themes": "^6.1.0",
    "ts-jest": "29.1.0",
    "ts-node": "10.9.1",
    "typescript": "~5.1.3",
    "webpack": "^5.87.0"
  }`

**Comment by Zarkos69** [comment]
Ok,
The problem seems to be Lottie and using that inside a Storybook. 
So might be the Storybook to version 7 that's the problem here.
My bad. I will have a look at that instead.

**Comment by arturovt** [comment]
Alright, I can upgrade the workspace to Angular 16 but the further issue is that the output code for the library likely won't be changed. So I don't think there's a reason to "re-publish" the package for now.

**Comment by Zarkos69** [comment]
Thanks for the quick response.
I finally got it fixed after realizing it's a Storybook issue...
For peeps that have the same issue: 
Don't declare your LottieModule in the Imports. But do the following inside the decorators tag:

` applicationConfig({
      providers: [importProvidersFrom(LottieModule.forRoot({ player: playerFactory }))],
    })`

**Comment by arturovt** [comment]
You can use `providers: [ provideLottieOptions({ player: ... }) ]`.
