### ISSUE TITLE
TypeError: Failed to resolve module specifier 'lottie-web/build/player/lottie.js'

### ISSUE THREAD

**Issue by mariogomesbarbosa** [ngx-lottie/ngx-lottie#17]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other: I can't make it work!
</code></pre>

## Current behavior

I'm following exactly  what said on documentation (or I think I am) but I'm getting this error:
"TypeError: Failed to resolve module specifier 'lottie-web/build/player/lottie.js'"

## Expected behavior
I expect to see my JSON animation rendered.

## Minimal reproduction of the problem with instructions

You can check my issue here: 
https://stackblitz.com/edit/angular-usa7nh

![image](https://user-images.githubusercontent.com/20422834/64039371-d7bf0680-cb30-11e9-94d6-cddb1c21b6b9.png)

## Environment

<pre><code>
Libs:
- @angular/core version: 8.2.4
- ngx-lottie version: 3.0.0

Browser:
- [x] Opera (desktop) version 63.0.3368.53

For Tooling issues:
- Platform: Windows

**Comment by arturovt** [comment]
Hey @mariogomesbarbosa!

Stackblitz doesn't support dynamic import for third-party libraries and the `lottie-web` library is loaded on demand via `import(...).then` as its size quite big.

I ran your reproduction locally, here is what I've got:

![image](https://user-images.githubusercontent.com/7337691/64481038-aacbbd00-d1dc-11e9-9563-e66ec3b1919b.png)

**Comment by mariogomesbarbosa** [comment]
Thanks @arturovt!
I was thinking that the problem was StackBlitz too. Thank you for confirm that to me!
