### ISSUE TITLE
error event is not called when any invalid json data gives

### ISSUE THREAD

**Issue by da201501245** [ngx-lottie/ngx-lottie#170]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
when we are giving invalid json data in options it is not calling error event.

## Expected behavior
it should call error event.

## Minimal reproduction of the problem with instructions
try any invalid json in options animationData

## Environment

<pre><code>
Libs:
- @angular/core version: 14
- ngx-lottie version: latest

yes
Browser:
- [*] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 18
- Platform:  Windows

Others:

</code></pre>

**Comment by arturovt** [comment]
Please provide a minimal reproducible example.

**Comment by arturovt** [comment]
Closing until a reproducible example is provided.
