### ISSUE TITLE
Support angular 16 and 17

### ISSUE THREAD

**Issue by wghglory** [ngx-lottie/ngx-lottie#172]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: X.Y.Z
- ngx-lottie version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by arturovt** [comment]
Isn’t it supported?

**Comment by arturovt** [comment]
Closing since leaking all of the information required in the issue template.
