### ISSUE TITLE
SVG Animation does not show properly and is requesting images

### ISSUE THREAD

**Issue by LiveLikeCounter** [ngx-lottie/ngx-lottie#18]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I want my svg animation to display on my angular-based website. But instead of showing the svg animation; it shows errors that some images ar missing. The result so far:

![image](https://user-images.githubusercontent.com/24720382/64331807-c31cbb80-cfd3-11e9-935e-7bde3a4e0c07.png)

## Expected behavior

If have tested the animation on a regular html page (from: https://github.com/airbnb/lottie-web/blob/master/demo/bodymovin/index.html) thats is working. See:

![image](https://user-images.githubusercontent.com/24720382/64332019-1abb2700-cfd4-11e9-8db5-69c30d2a55a9.png)

## Minimal reproduction of the problem with instructions

* Step 1: Follow the steps in the usage: https://www.npmjs.com/package/ngx-lottie#usage
* Step 2: I only have a different location for my exported animation.json as the example, please see:

![image](https://user-images.githubusercontent.com/24720382/64331565-51447200-cfd3-11e9-9197-1205ccffcda0.png)

## What is the motivation / use case for changing the behavior?

I want to show the animation :)

## Environment

<pre><code>
Libs:
  "dependencies": {
    "@angular/animations": "^8.2.5",
    "@angular/cdk": "^8.1.4",
    "@angular/common": "^8.2.5",
    "@angular/compiler": "^8.2.5",
    "@angular/core": "^8.2.5",
    "@angular/fire": "^5.2.1",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "^8.2.5",
    "@angular/material": "^8.1.4",
    "@angular/platform-browser": "^8.2.5",
    "@angular/platform-browser-dynamic": "^8.2.5",
    "@angular/platform-server": "^8.2.5",
    "@angular/router": "^8.2.5",
    "@nguniversal/express-engine": "^8.1.1",
    "@nguniversal/module-map-ngfactory-loader": "8.1.1",
    "core-js": "^3.2.1",
    "express": "^4.17.1",
    "firebase": "^6.5.0",
    "hammerjs": "^2.0.8",
    "lottie-web": "^5.5.8",
    "moment": "^2.24.0",
    "ngx-lottie": "^3.0.0",
    "npm-check-updates": "^3.1.21",
    "rxjs": "^6.5.3",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.16.0
- Platform:  Mac, Linux, Windows

</code></pre>

**Comment by arturovt** [comment]
Hey! Could you give me your `headanimation.json`? I'm not able to do anything until I can debug it. Some reproduction or stackblitz example would be great.

**Comment by LiveLikeCounter** [comment]
Hi, thank you for your response.
See the animation-json file here:
[headeranimation.zip](https://github.com/ngx-lottie/ngx-lottie/files/3589563/headeranimation.zip)

I never use StackerBlitz before. If this doesn't help you, I'll look after the StackerBlitz.

**Comment by LiveLikeCounter** [comment]
Hi, thanks for your reply.

I've made this [Stackblitz](https://stackblitz.com/edit/lottie-exxample-animation). But unfortunately  I did not made it to reproduce the problem. Therefor another problem raised. I hope know how to solve...

**Comment by arturovt** [comment]
@LiveLikeCounter this is a stackblitz issue. There was [the same](https://github.com/ngx-lottie/ngx-lottie/issues/17#issuecomment-529153574) issue some days ago. You could just create a github repo.

**Comment by arturovt** [comment]
@LiveLikeCounter hey. To not keep this issue opened I would like to help you to resolve the problem. I've published the ngx-lottie@v4 so it's possible to provide player synchronously. Thus stackblitz might be working.

**Comment by LiveLikeCounter** [comment]
@arturovt thank you for your response. sorry for my late answer.
I've updated the package, but get the following error:
![Screen Shot 2019-09-26 at 10 52 43](https://user-images.githubusercontent.com/24720382/65673877-f0e1a700-e04b-11e9-9e52-f5cbad59cd25.png)

After I updated the imports based on the documentation 👌

I get the following error (the page isn't rendered):
![Screen Shot 2019-09-26 at 11 07 41](https://user-images.githubusercontent.com/24720382/65675166-0eb00b80-e04e-11e9-9c43-f9733c543dbe.png)

My component looks like:
```
import { Component } from '@angular/core';
import { AnimationItem } from 'lottie-web';
import { LottieOptions } from 'ngx-lottie';
 
@Component({
  selector: 'app-headeranimarion',
  template: `
  <ng-lottie
    [options]="options"
    (animationCreated)="animationCreated($event)">
  </ng-lottie>
  `,
  styles: ['h1 { font-weight: normal; }']
})

export class HeaderAnimationComponent {
  public options: LottieOptions = {
    path: 'assets/animations/headeranimation.json',
    // renderer: 'svg',
    // autoplay: true,
    // loop: false,
    // autoloadSegments: true,
  };
 
  public animationCreated(animationItem: AnimationItem): void {
    console.group('LOTTIE:')
    console.log(animationItem);
  }
}
```

**Comment by arturovt** [comment]
@LiveLikeCounter see README. It requires calling `forRoot` right now if you've installed the v4.

**Comment by LiveLikeCounter** [comment]
Thanks for your patience. If tried it now with the forRoot and so on, but still:

![image](https://user-images.githubusercontent.com/24720382/66210404-07c27200-e6ba-11e9-822a-616045a6adae.png)

I will stick with an mp4 for now. Thanks for making time to try help it out!
