### ISSUE TITLE
How can i change text  in an animation dynamically?

### ISSUE THREAD

**Issue by Kapparow** [ngx-lottie/ngx-lottie#182]
Hello, i use an animation that has some text in it. How can i dynamically change text in that? I've looked at lottie-web, there is a documentation about it. It says with updating animation data i can change text. How can i do it with ngx-lottiie ?

**Comment by arturovt** [comment]
Can you provide a link to documentation how it's done in lottie-web?

**Comment by arturovt** [comment]
You can get the animation item by listening to `animationCreated` event and then do the same stuff that's mentioned in the docs: `this.animationItem.renderer.elements[0].updateDocumentData({t:'new text', s:20},0)`
