### ISSUE TITLE
Please add support for renderers other than svg

### ISSUE THREAD

**Issue by jensroth-git** [ngx-lottie/ngx-lottie#183]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

unable to set renderer to anything but svg which is horrible on iOS safari
`
  options: AnimationOptions = {
    renderer: 'canvas',
    path: '/assets/bodymovin/logo.json',
    assetsPath: '/assets/bodymovin/images/',
  };`

## Expected behavior

be able to set renderer to all supported ones by lottie-web

## What is the motivation / use case for changing the behavior?

iOS safari has horrible support for svg rendering, canvas works much better

## Environment

<pre><code>
Libs:
- @angular/core version: 17.3.0
- ngx-lottie version: 11.0.2
- lottie-web version: 5.12.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [x ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by arturovt** [comment]
This is supported through the lottie-web typings `options: AnimationOptions<'canvas'> = { renderer: 'canvas' } ...`
