### ISSUE TITLE
Issue in lottie SSR

### ISSUE THREAD

**Issue by Dhan3777** [ngx-lottie/ngx-lottie#185]
Imports Here

```

@NgModule({
  declarations: [],
  imports: [],
  providers: [
    provideLottieOptions({
      player: () => player,
    }),
    provideCacheableAnimationLoader(),
    provideServerRendering(),
    provideLottieServerOptions({
      preloadAnimations: {
        folder: 'dist/browser/assets',
        animations: ['wave_home.json'],
      },
    }),
    provideHttpClient(
      withFetch(),
      withInterceptors([errorHandleInterceptor]),
    ),
    provideClientHydration(withHttpTransferCacheOptions({
      includePostRequests: true
    })),
    provideAnimationsAsync(),
    { provide: LOCALE_ID, useValue: "en-IN" }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

when I do ng build . Getting following error
✘ [ERROR] Could not resolve "node:path"

    node_modules/ngx-lottie/fesm2022/ngx-lottie-server.mjs:3:21:
      3 │ import { join } from 'node:path';
        ╵                      ~~~~~~~~~~~

  The package "node:path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "fs"

    node_modules/ngx-lottie/fesm2022/ngx-lottie-server.mjs:5:25:
      5 │ import { readFile } from 'fs';
        ╵                          ~~~~

  The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

**Comment by arturovt** [comment]
No, there’s an issue in your typings. Angular’s SSR config by default supports Node typings.

**Comment by vanvantsyan** [comment]
have the same issue , can someone help with it ?
