### ISSUE TITLE
Support for Angular 18

### ISSUE THREAD

**Issue by Michael-Schubert55** [ngx-lottie/ngx-lottie#186]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
No support of Angular 18

## Expected behavior
ngx-lottie works with Angular 18

## What is the motivation / use case for changing the behavior?
Keeping lottie up to date with new versions of Angular.

## Environment

<pre><code>
Libs:
- @angular/core version: 18.1.0
- ngx-lottie version: 11.0.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by arturovt** [comment]
`v12.0.0`.
