### ISSUE TITLE
No provider for InjectionToken LottieOptions

### ISSUE THREAD

**Issue by NicolasR** [ngx-lottie/ngx-lottie#190]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I get an error: **No provider for InjectionToken LottieOptions** with this configuration

Declaration component:
```
@Component({
  selector: "lottie-preview-wrapper",
  template: ` <ng-lottie #lottieContainer [options]="updatedOptions" (animationCreated)="animationCreated($event)"></ng-lottie>`,
  standalone: true,
  imports: [LottieComponent],
  providers: [provideLottieOptions({player: playerFactory}), provideCacheableAnimationLoader()],
})
```

This works:
```
@Component({
  selector: "lottie-preview-wrapper",
  template: ` <ng-lottie #lottieContainer [options]="updatedOptions" (animationCreated)="animationCreated($event)"></ng-lottie>`,
  standalone: true,
  imports: [LottieComponent],
  providers: [AnimationLoader, { provide: ɵLOTTIE_OPTIONS, useValue: { useWebWorker: true, player: playerFactory } }],
})
```

## Expected behavior

I expect component as it used to be in version 8.

## Environment

<pre><code>
Libs:
- @angular/core version: 17.3.11
- ngx-lottie version: 11.0.2

Browser:
- [X] Chrome (desktop) version 131
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 20.9.0  
- Platform:  Windows

Others:

</code></pre>

**Comment by arturovt** [comment]
`provideLottieOptions` returns environment providers which are expected to be used in the application config. There's no reason to provide a player on the component level.

**Comment by Kamilius** [comment]
Is there a way to use `ngx-lottie` with Angular 18, but AppModule-based application?
Tried using `provideLottieOptions` inside `AppModule providers`, but this yields the same error, as the one specified by author... :(
