### ISSUE TITLE
Ngx-Lottie is not working properly.

### ISSUE THREAD

**Issue by HarshitChhipa** [ngx-lottie/ngx-lottie#34]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have followed the documentation exactly and it is still giving the error.

![Screenshot 2019-10-22 at 8 58 19 PM](https://user-images.githubusercontent.com/18600762/67302764-047b1300-f50f-11e9-9bbd-2ab888683910.png)

## Expected behavior

It should have worked as per the docs.

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
Please let me know if there is anything missing in the docs.
Or what can be caused by the above error.

These are the dependencies.

  "dependencies": {
    "@angular/common": "7.2.15",
    "@angular/core": "7.2.15",
    "@angular/forms": "7.2.15",
    "@angular/http": "7.2.15",
    "@angular/platform-browser": "7.2.15",
    "@angular/platform-browser-dynamic": "7.2.15",
    "@angular/router": "7.2.15",
    "@ionic-native/app-availability": "5.13.0",
    "@ionic-native/appsflyer": "5.13.0",
    "@ionic-native/branch-io": "5.13.0",
    "@ionic-native/camera": "^5.15.0",
    "@ionic-native/clevertap": "5.13.0",
    "@ionic-native/clipboard": "5.13.0",
    "@ionic-native/code-push": "5.13.0",
    "@ionic-native/core": "5.13.0",
    "@ionic-native/diagnostic": "5.13.0",
    "@ionic-native/firebase": "5.13.0",
    "@ionic-native/geolocation": "5.13.0",
    "@ionic-native/http": "5.13.0",
    "@ionic-native/in-app-browser": "5.13.0",
    "@ionic-native/market": "5.13.0",
    "@ionic-native/network": "5.13.0",
    "@ionic-native/social-sharing": "5.13.0",
    "@ionic-native/splash-screen": "5.13.0",
    "@ionic-native/status-bar": "5.0.0",
    "@ionic/angular": "4.8.1",
    "@ionic/storage": "2.2.0",
    "@juspay/ec-headless-cordova-plugin": "1.0.8",
    "appcenter-cli": "2.2.1",
    "branch-cordova-sdk": "3.2.0",
    "clevertap-cordova": "2.1.2",
    "cordova-android": "^8.0.0",
    "cordova-android-support-gradle-release": "3.0.1",
    "cordova-browser": "6.0.0",
    "cordova-clipboard": "1.3.0",
    "cordova-ios": "^5.0.1",
    "cordova-plugin-advanced-http": "2.1.1",
    "cordova-plugin-androidx": "1.0.2",
    "cordova-plugin-androidx-adapter": "1.1.0",
    "cordova-plugin-appavailability": "0.4.2",
    "cordova-plugin-appsflyer-sdk": "4.4.20",
    "cordova-plugin-camera": "4.1.0",
    "cordova-plugin-code-push": "1.12.0",
    "cordova-plugin-device": "2.0.3",
    "cordova-plugin-dialogs": "2.0.1",
    "cordova-plugin-enable-multidex": "0.2.0",
    "cordova-plugin-file": "6.0.2",
    "cordova-plugin-file-transfer": "1.7.1",
    "cordova-plugin-firebasex": "6.1.0",
    "cordova-plugin-geolocation": "4.0.2",
    "cordova-plugin-inappbrowser": "3.1.0",
    "cordova-plugin-ionic-keyboard": "2.2.0",
    "cordova-plugin-ionic-webview": "4.1.1",
    "cordova-plugin-market": "1.2.0",
    "cordova-plugin-network-information": "2.0.2",
    "cordova-plugin-packagemanager": "0.1.7",
    "cordova-plugin-splashscreen": "5.0.3",
    "cordova-plugin-statusbar": "2.4.3",
    "cordova-plugin-whitelist": "1.3.4",
    "cordova-plugin-x-socialsharing": "5.6.0",
    "cordova-plugin-zip": "3.1.0",
    "cordova-sqlite-storage": "3.3.0",
    "cordova.plugins.diagnostic": "3.9.2",
    "core-js": "2.6.9",
    "es6-promise-plugin": "4.2.2",
    "hammerjs": "2.0.8",
    "lottie-web": "^5.5.9",
    "moment": "2.24.0",
    "ngx-lottie": "^5.2.0",
    "ngx-moment": "3.4.0",
    "rxjs": "6.5.3",
    "scroll-into-view": "1.9.7",
    "sentry-cordova": "0.15.0",
    "tslib": "1.10.0",
    "xml2js": "0.4.22",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/architect": "0.13.9",
    "@angular-devkit/build-angular": "0.13.9",
    "@angular-devkit/core": "7.3.9",
    "@angular-devkit/schematics": "7.3.9",
    "@angular/cli": "7.3.9",
    "@angular/compiler": "7.2.15",
    "@angular/compiler-cli": "7.2.15",
    "@angular/language-service": "7.2.15",
    "@ionic/angular-toolkit": "1.5.1",
    "@ionic/lab": "1.0.24",
    "@types/jasmine": "2.8.16",
    "@types/jasminewd2": "2.0.6",
    "@types/node": "10.14.18",
    "codelyzer": "4.5.0",
    "jasmine-core": "2.99.1",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.0.6",
    "karma-jasmine": "1.1.2",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.4.2",
    "ts-node": "8.1.1",
    "tslint": "5.16.0",
    "typescript": "3.1.6"
  },

**Comment by arturovt** [comment]
Hey. Could you provide some reproduction (codesandbox/stackblitz/github repo)? Because there are E2E tests + server-side rendering running on the CircleCI. I've never seen such error and cannot reproduce it locally.

**Comment by HarshitChhipa** [comment]
Hey, dude Thanks for answering.
I will provide you a demo on GitHub or Stackblitz.

**Comment by HarshitChhipa** [comment]
I guess there is no issue with your package as I am using a fixed version of typescript and your package needs a different version so it is not compiling the code properly so i had to drop the ngx-lottie and instead I switched to ng-lottie which is more compatible to my existing codebase however Thanks for help it is working awesome with the latest version.

**Comment by HeshamEG** [comment]
I switched to ng-lottie also
