### ISSUE TITLE
How to stop all animations globally

### ISSUE THREAD

**Issue by elesueur** [ngx-lottie/ngx-lottie#37]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently, to stop an animation, I need to get a reference to each AnimationItem and call stop().

## Expected behavior
In order to support a global switch to disable animations, it would be preferable to have a providedIn: 'root' service that all ng-lottie instances listen to in order to disable every animation.

This might be desirable to support, for example, a motionless mode for visually impaired users who might want to disable animations because they are distracting or cause readability problems.

**Comment by arturovt** [comment]
What do you think of a single function that would give the ability to loop all living animation items and do whatever you want with them?
```ts
import { forEachAnimatiomItem } from 'ngx-lottie';

stopAllAnimationsButton.addEventListener('click', () => {
  forEachAnimationItem(animationItem => animationItem.stop());
});
```

This would allow you to do anything with any existing animation item, not only stop it.

**Comment by elesueur** [comment]
I think this needs a bit more thought... I started doing some work on this, but ran out of time today.

It needs to also ensure that any new ng-lottie instances that are created are also never started if animations are globally disabled, for example.

Etienne

**Comment by arturovt** [comment]
Gonna close this issue due to inactivity.

After thinking I consider this request to be out of scope for this package since its purpose is to render animations. This feature can be kept out of the framework.
