### ISSUE TITLE
I got a compiling error after fresh install

### ISSUE THREAD

**Issue by Toomavic** [ngx-lottie/ngx-lottie#38]
After fresh install as described in the docs, I got this error
![image](https://user-images.githubusercontent.com/10185045/70905215-01326e00-200c-11ea-817f-7156b1714560.png)

I am using Angular Core ^5.2.0

**Comment by arturovt** [comment]
It's intended to be used with Angular 8+ and Ivy renderer :) Angular 5 is not even supported by Google team, it's just too old already :wink:

**Comment by Toomavic** [comment]
It happens to use old version and you can't upgrade to latest and the whole app got crashed. It's bad but it should have a solution as well!

I managed to make it work with custom web component and I upgraded my Typescript to be larger than 2.7.2

Once I do a successful migrate, I may use your package 😉😉

**Comment by arturovt** [comment]
Good news! :wink: 

Yeah. You should be considering that Google also drops support for old Angular versions (5 now and will be 6 after 9 is out) and libraries should do it either.
