### ISSUE TITLE
`containerClass` input only allows one class

### ISSUE THREAD

**Issue by shaungrady** [ngx-lottie/ngx-lottie#44]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```html
<ng-lottie
  containerClass="one two"
></ng-lottie>
```
```
Caught Runtime Error. DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('one two') contains HTML space characters, which are not valid in tokens.
```

## Expected behavior

Both classes should be assigned to the container.

## Minimal reproduction of the problem with instructions

See above example. Root cause:

https://github.com/ngx-lottie/ngx-lottie/blob/master/src/src/lottie.component.ts#L46

Should be split on spaces and iteratively added, perhaps? Under the hood it's calling `element.classList.add` which only accepts one class. Example:

```js
document.body.classList.add('one two')
```

## What is the motivation / use case for changing the behavior?

Having a one-class limitation seems arbitrary.

## Environment

<pre><code>
Libs:
- @angular/core version: 8.2.14
- ngx-lottie version: 5.3.2

Browser:

All.

**Comment by arturovt** [comment]
@shaungrady 

Hey. I've published `5.4.0`. Could you give it a try?
