### ISSUE TITLE
iOS Dark Background in Lottie Animation (Ionic 5)

### ISSUE THREAD

**Issue by dennissch** [ngx-lottie/ngx-lottie#49]
## I have a problem with the integration of a Lottie animation. Under web and on Android devices everything works perfectly, but under iOS I get a black background and can't understand why.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current & Expected behavior

![lottie-issue-ios](https://user-images.githubusercontent.com/5501411/77746740-b3bb9900-701d-11ea-9aca-97009d5cdf13.jpg)

## Minimal reproduction of the problem with instructions

* Template: 
```html
<div class="lottie-wrapper">
	<ng-lottie [options]="lottieIntroConfig" [styles]="lottieIntroStyle" containerClass="lottie-wrapper" (domLoaded)="lottieDomLoaded()" (animationCreated)="lottieAnimationCreated($event)"></ng-lottie>
</div>
```

* CSS:
```css
div.lottie-wrapper {
	width: var(--lottie-width);
	margin-left: calc((var(--lottie-width) - 100%) / 2 * -1);
	margin-top: var(--lottie-top);
}
```

* Typescript: 
```typescript
public lottieIntroConfig: AnimationOptions = {
	path: '/assets/lottie/parnassia_intro.json',
	autoplay: true
};

// also these settings have no effect
public lottieIntroStyle: Partial<CSSStyleDeclaration> = {
	background: '#fff',
	backgroundAttachment: '#fff',
	backgroundClip: '#fff',
	backgroundColor: '#fff',
	backgroundImage: '#fff',
	backgroundOrigin: '#fff',
	fill: '#fff'
}
```

## Environment

<pre><code>Libs:
- "@angular/core": "^9.1.0"
- "@ionic/angular": "^5.0.7"
- "cordova-android": "^8.1.0"
- "cordova-ios": "^5.1.1"
- "ngx-lottie": "^5.4.0"
 
For Tooling issues:
- Node.js version: v10.19.0
- Cordova CLI version: 9.0.3 (cordova-lib@9.0.2)
- npm version: 6.13.4
- macOS version: 10.14.6
- Xcode version: Xcode 11.0 (Build version 11A420a )</code></pre>

Thanks in advance!
Best, Dennis

**Comment by arturovt** [comment]
Hello.

Could you try to render animation using `lottie-web` API directly? If it shows the same then it's related to iOS and `lottie-web` itself.

**Comment by arturovt** [comment]
Also would be great if you create a _minimal reproducible example_ that I can clone and test, because there are E2E and Unit tests running on Circle that cover this stuff

**Comment by dennissch** [comment]
Hi @arturovt,
I have tested the integration directly with lottie-web and everything looks right here. I could also test the behaviour directly in the simulator.

![asd](https://user-images.githubusercontent.com/5501411/77828042-9d930300-7119-11ea-99c5-e860fc9d1f86.jpg)

For the right example the following configuration was used:
```
<div id="bm"> </div>
<script src="assets/lottie/lottie.min.js" type="text/javascript"></script>
<script>
	var animation = bodymovin.loadAnimation({
		container: document.getElementById('bm'),
		renderer: 'svg',
		loop: true,
		autoplay: true,
		path: 'assets/lottie/parnassia_intro.json'
	})
</script>
```

Here I have uploaded the minimal reproducible example:
https://github.com/dennissch/lottie-angular-example

Thank you very much for your support.
Best, Dennis

**Comment by arturovt** [comment]
Thank you for providing this info. I will look at it as soon as possible.

**Comment by dennissch** [comment]
Hi @arturovt, unfortunately the issue is still present. Could you already take a closer look into it or do you have another tip for me?

**Comment by arturovt** [comment]
Hey man, sorry for delay...

I've just cloned your git repo and run `ng serve` and `ionic serve`:

![desktop](https://user-images.githubusercontent.com/7337691/80753245-9ce4f680-8b35-11ea-8c22-a20c933caa02.png)

**Comment by arturovt** [comment]
@orenagiv this seems like it's related to what you've said regarding black background right?

**Comment by dennissch** [comment]
Hi @arturovt, exactly, the error only shows up under iOS - either in a simulator or on a native device. Under Android and Web everything works, only under iOS a black background is displayed (see my description from above). If the animation are inserted directly with lottie-web, this also works.

I am very thankful for every idea.

**Comment by orenagiv** [comment]
Yes @arturovt 
It seems like the same issue as https://github.com/ngx-lottie/ngx-lottie/issues/24

**Comment by arturovt** [comment]
Ok, it's hard for me to reproduce an issue. Thus I will publish beta version to give you a chance to test it.

**Comment by orenagiv** [comment]
Thanks @arturovt !
I'll be glad to!

**Comment by arturovt** [comment]
I have published `6.0.0-beta.0`, it has a restriction `lottie-web >= 5.4.0`, I removed setting location href there on Safari. Could you give it a try?

**Comment by orenagiv** [comment]
Works like a charm @arturovt !
THANKS! :))

**Comment by arturovt** [comment]
@orenagiv thank you for checking!
@dennissch now I'm waiting for your check :smile:

**Comment by dennissch** [comment]
it works! thanks @arturovt

**Comment by arturovt** [comment]
I will publish `6.0.0` then. Thank you for helping guys.

**Comment by arturovt** [comment]
`6.0.0` has been published.
