### ISSUE TITLE
is possible active only when hover?

### ISSUE THREAD

**Issue by chobijaeyu** [ngx-lottie/ngx-lottie#53]
hi 
good gay.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected behavior

if have hover option will be better

here is lottie-player example.

```
      <h3>Play animation on hover with loop intermission</h3>
      <lottie-player
        src="https://assets4.lottiefiles.com/datafiles/zc3XRzudyWE36ZBJr7PIkkqq0PFIrIBgp4ojqShI/newAnimation.json"
        style="width: 400px;"
        loop
        hover
        intermission="1000"
      ></lottie-player>
```

**Comment by arturovt** [comment]
I guess you've opened an issue in the wrong repository ;)

**Comment by arturovt** [comment]
Move your issue here:

https://github.com/LottieFiles/lottie-player

**Comment by chobijaeyu** [comment]
how about this?

```
<ng-lottie
  [options]="options"
  hover="true"
></ng-lottie>
```

**Comment by arturovt** [comment]
@chobijaeyu 

If I understand you correctly you wanna play your animation only if the user hovers the block. Then you can implement it in a few lines of code:

```ts
@Component({
  template: `
    <ng-lottie
      [options]="options"
      (animationCreated)="animationItem = $event"
      (mouseover)="animationItem?.play()"
      (mouseleave)="animationItem?.pause()"
    ></ng-lottie>
  `,
})
class MyComponent {
  options = {
    ...,
    autoplay: false,
  };

  animationItem: AnimationItem | null = null;
}
```

**Comment by chobijaeyu** [comment]
@arturovt thanks.
it's works.
