### ISSUE TITLE
No way of delaying clean-up of animation if used with ngAnimate

### ISSUE THREAD

**Issue by rsouthgate** [ngx-lottie/ngx-lottie#71]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

ngx-lottie onDestroy removes and unloads the animation. When used in conjunction with ngAnimate there is no allowance for a :leave animation to run while preserving the running on the lottie animation

## Expected behavior
While the component is still in the DOM the animation should still run. While still preserving the cleanup after the element is removed.

## Minimal reproduction of the problem with instructions

This should demonstrate the issue: https://angular-ivy-jvi5bm.stackblitz.io/

When toggling the angular animation in the lottie animation runs as soon as the json is available (in the demo it's bundled in the component - so immediately).
When toggling the angular animation out the ngDestroy fires before the animation runs and the animation is removed - leaving just the container to fade out.

## What is the motivation / use case for changing the behavior?
While it's goof that the library tidies up animations it would be nice to preserve the running animation while exiting from the dom.

I don't know if this is possible via some ngAnimate hooks, but if not could a delay option be provided to the ngx-lottie component such that it's ngDestroy waits the delay period before tidying. Then I could pass the animation time through.

## Environment

<pre><code>
Libs:
- @angular/core version: 10.0.12
- ngx-lottie version: 4.6.0

Browser:
- [x] Chrome (desktop) version 84
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: N/A
- Platform:  All

Others:
</code></pre>

**Comment by arturovt** [comment]
Hey. This library is not meant to do anything with Angular internals ;) Because, unfortunately (or fortunately) this is how Angular transition engine works, it overrides `RendererFactory2` and provides a new `Renderer2` with its `removeChild` implementation, which firstly runs animations, listens to `animationEnd` event and then removes DOM nodes. And of course it runs lifecycle hooks on all components before removing DOM nodes.

You could try to create some wrapper for this e.g. `app-animation-wrapper`, setup `@keyframes` and style its host via `:host` and apply those keyframes to the host. The next step is to listen to `@HostListener('animationend')` and render/un-render the content inside this wrapper. The content can be provided via `ng-content` or `ng-template` and created via `TemplateRef` (there are hundreds of solutions).

**Comment by rsouthgate** [comment]
@arturovt If I understand correctly you are saying I should not use :leave animation and instead rely on some other state to state animation and manually trigger the removal of components once that state to state animation has ended. Thus delaying the onDestroy until the angular animation has completed?

While this will work it does mean I can't leverage the simplicity of the :leave pseudo animation state. But I was thinking this library's baseDirective could offer an `@Input destroy$:Subject<void>` that would override the private `[destroy$](https://github.com/ngx-lottie/ngx-lottie/blob/53b7175747f189db8e051208a197b5bafe618378/src/src/base.directive.ts#L99)` subject which would allow me to pass in a subject whose completion I could control externally?

Not sure if that is trivial given the other animationItems$ destroy called in destroyAnimation method, but if you don't think this is a terrible idea I'd be happy to fork this and try it out.

**Comment by arturovt** [comment]
Closing per this comment https://github.com/ngx-lottie/ngx-lottie/issues/71#issuecomment-679736588

As I mentioned there're solutions for solving this issue. In the most extreme case you can override the `destroy$` property on the instance:

```ts
myDestroy$ = new Subject<void>();

@ViewChild(LottieComponent, { static: true })
set lottie(lottie: LottieComponent) {
  lottie['destroy$'] = this.myDestroy$;
}
```
