### ISSUE TITLE
No provider for AnimationLoader

### ISSUE THREAD

**Issue by maykon-oliveira** [ngx-lottie/ngx-lottie#75]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I followed the README.md guide to setup ngx-lottie lib to use in a Ionic/Angular projet, but I am facing a issue to use.

## Minimal reproduction of the problem with instructions

```ts
import { LottieModule } from "ngx-lottie";

export function playerFactory() {
  return import(/* webpackChunkName: 'lottie-web' */ "lottie-web");
}

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    EarnRewardModalPageRoutingModule,
    LottieModule.forRoot({ player: playerFactory }),
  ],
  declarations: [EarnRewardModalPage],
})
export class EarnRewardModalPageModule {}
```
```
ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(Tab2PageModule)[AnimationLoader -> AnimationLoader -> AnimationLoader -> AnimationLoader -> AnimationLoader]: 
  NullInjectorError: No provider for AnimationLoader!
NullInjectorError: R3InjectorError(Tab2PageModule)[AnimationLoader -> AnimationLoader -> AnimationLoader -> AnimationLoader -> AnimationLoader]: 
  NullInjectorError: No provider for AnimationLoader!
    at NullInjector.get (core.js:915)
    at R3Injector.get (core.js:11082)
    at R3Injector.get (core.js:11082)
    at R3Injector.get (core.js:11082)
    at NgModuleRef$1.get (core.js:24199)
    at R3Injector.get (core.js:11082)
    at NgModuleRef$1.get (core.js:24199)
    at R3Injector.get (core.js:11082)
    at NgModuleRef$1.get (core.js:24199)
    at Object.get (core.js:22102)
    at resolvePromise (zone-evergreen.js:798)
    at zone-evergreen.js:705
    at rejected (tslib.es6.js:72)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:27437)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27425)
```

## Environment

<pre><code>
Libs:
- "@angular/core": "~10.0.0",
- "lottie-web": "^5.7.3"
- "ngx-lottie": "^6.4.0",

Browser:
- [ x] Chrome (desktop) version XX
- [ x] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by arturovt** [comment]
Could you provide a minimal reproducible example?

**Comment by arturovt** [comment]
Closing this as _not reproducible_ and _not an issue_. You have to provide the `LottieModule.forRoot` in the `AppModule` and not in some feature module. I see that it ended up searching `AnimationLoader` in `Tab2PageModule` module but you provide `LottieModule` in `EarnRewardModalPageModule`.
