### ISSUE TITLE
lottie-web Methods Availability

### ISSUE THREAD

**Issue by jboothe** [ngx-lottie/ngx-lottie#77]
## lottie-web Methods Availability
Does `ngx-lottie` provide access to the main `lottie-web` methods documented [here](https://github.com/airbnb/lottie-web/blob/master/README.md#usage)? 

Primarily:

- goToAndPlay
- goToAndStop
- setDirection
- playSegments

<pre><code>
Libs:
- @angular/core version: 9.0.4
- ngx-lottie version: 6.4.0
</code></pre>

Thanks, 
Jeff

**Comment by arturovt** [comment]
`goToAndPlay` is a method on the `AnimationItem.prototype`, you get the `AnimationItem` via `animationCreated` event and then you can those methods:
```ts
@Component({
  template: `
    <ng-lottie [options]="options" (animationCreated)="animationCreated($event)"></ng-lottie>
  `
})
class LottieComponent {
  options = { ... }

  animationCreated(animationItem: AnimationItem) {
    animationItem.goToAndPlay(...)
  }
}
```

**Comment by jboothe** [comment]
Thank you @arturovt. That is fantastic!

**Comment by generated** [comment]
Might be worth to mention this in the docs. As a newcomer to lottie i was looking for this quite some time
