### ISSUE TITLE
Access Timeline Markers? 

### ISSUE THREAD

**Issue by jboothe** [ngx-lottie/ngx-lottie#78]
## Access Timeline Markers?

How would you recommend accessing the `markers` property located at:

`AnimationItem.animationData.markers`

The current typings do not allow access to it. 

<pre><code>
Libs:
- @angular/core version: 9.0.4
- ngx-lottie version: 6.4.0
</code></pre>

Thanks, 

Jeff

**Comment by arturovt** [comment]
The `animationData` is not exposed by `lottie-web` typings. But if you need it you can use the old property access style:
```ts
const markers = animationItem['animationData'].markers
```
