### ISSUE TITLE
Compatibility angular 8 

### ISSUE THREAD

**Issue by jankowskip** [ngx-lottie/ngx-lottie#81]
- [x] Other- Question

Hey, im using angular 8.2.9 and everything works fine, i dont need `markDirty` or `detectChanges` features, are there any known issues for most basic usage in angular 8? 

## Current behavior
Works fine

## Expected behavior
Shouldnt work? 

## Environment

<pre><code>
Libs:
 "@angular/core": "~8.2.9",
"lottie-web": "^5.7.4",
"ngx-lottie": "^6.4.0",

**Comment by arturovt** [comment]
Hey, I haven't checked the latest version with Angular 8. I can only say that it's compatible with Angular 9+.

**Comment by arturovt** [comment]
I will close that issue for now. Feel free to re-open if I'm missing anything or you've got other questions.
