### ISSUE TITLE
Dynamic Text updating animationData

### ISSUE THREAD

**Issue by jboothe** [ngx-lottie/ngx-lottie#82]
I am trying to replace text dynamically in a lottie file similar what Hernan recommends in a plain Javascript approach here:
https://github.com/airbnb/lottie-web/issues/238#issuecomment-650824046

```
animationCreated(animationItem: AnimationItem): void {
    let aData = animationItem["animationData"];
    aData.layers[0].t.d.k[0].s.t = "New Value";
}
```

However, I'm not clear on how this would work with your prescribed [updateAnimation](https://github.com/ngx-lottie/ngx-lottie#updating-animation) since it is expecting a json URL and not a modified json file in memory. 

Can you offer the best approach using ngx-lottie?

Thanks!

**Comment by jboothe** [comment]
Essentially, I'm looking to refire `loadAnimation` after making changes to `animationItem.animationData`. Does ngx-lottie provide an API to that?

**Comment by arturovt** [comment]
> since it is expecting a json URL and not a modified json file in memory.

It expects any kind of options :) I haven't tested this code but give it a try:

```ts
@Component({
  template: `
    <ng-lottie
      [options]="options"
      (animationCreated)="animationItem = $event"
    ></ng-lottie>

    <button (click)="updateAnimationData()">Update animation data</button>
  `,
})
export class TestComponent {
  options: AnimationsOptions = {
    path: '/assets/animation.json',
  };

  animationItem: AnimationItem;

  updateAnimationData() {
    let aData = this.animationItem['animationData'];
    aData.layers[0].t.d.k[0].s.t = 'New Value';

    this.options = {
      ...this.options,
      animationData: aData,
    };
  }
}
```

**Comment by arturovt** [comment]
Closing per code above. Feel free to re-open if I'm missing something.
