### ISSUE TITLE
div container at Runtime

### ISSUE THREAD

**Issue by adelemam** [ngx-lottie/ngx-lottie#84]
## I'm submitting a...

<pre><code>
[ ] Feature request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I want to convert any div to a lottie player at run time ( without adding lottie player tag ) , so any div can be converted to animating player while data is loading , then after done it convert back to its normal behaviour

I couldn't get such feature in your documentation and wondering if it is exist or not, 
can you help please

**Comment by arturovt** [comment]
Not sure I'm following your question. Could you provide more context?

**Comment by adelemam** [comment]
sorry , I have found an option to only add lottie directive to any div and make it container for animation. but i cannot control its styles programatically ( as lottie directive only binds to options)

so my updated question now how to update styles for lottie directive ( not <ng-lottie > )

**Comment by arturovt** [comment]
What do you mean by updating styles for directive? Directives are bound to single HTML elements that are controlled by you, you can apply any custom CSS to them.

**Comment by adelemam** [comment]
Ok, lets talk by sample code , 
Here is the usage of normal lottie component 
```
<ng-lottie 
width="100px"
height="100px"
[options]="options" [styles]="styles" ></ng-lottie>

in this sample you can manage styles normally from code using this code 

 ```
```
styles: Partial<CSSStyleDeclaration> = {
    maxWidth: '190px',
    maxHeight:'10px',
    margin: '0 auto',
  };
```

but unfortunately we cannot use `ng-lottie` as we want to convert any div to lottie player using the lottie directive as below 

`<div  lottie [options]="options"  style="width: 300px;height: 300px;" id="animationDiv" (animationCreated)="animationCreated1($event)">`

not in previous example we cannot bind to styles ( as it is not available (don't know why) , and style tag doesn't work on the player itself ( just work on the div)

so can you help please?

**Comment by adelemam** [comment]
hello @arturovt  , can you help please ?
