### ISSUE TITLE
updating styles for lottie directive

### ISSUE THREAD

**Issue by adelemam** [ngx-lottie/ngx-lottie#85]
## I'm submitting a...

[ ] Feature request

</code></pre>

Is there is ability to update lottie styles from code , as lottie directive only binds to options

**Comment by webocrat** [comment]
it should also bind styles.
[styles]

`@Input() styles: Partial<CSSStyleDeclaration> | null = null;`
[see base directive here](https://github.com/ngx-lottie/ngx-lottie/blob/master/src/src/base.directive.ts)

**Comment by arturovt** [comment]
As @webocrat mentioned there is a `styles` binding, it's bound directly to `div` container internally, tho you can easily modify `ng-lottie` element styles through `style` or `ngStyle` bindings.
