### ISSUE TITLE
dotLottie support

### ISSUE THREAD

**Issue by Majed93** [ngx-lottie/ngx-lottie#86]
## I'm submitting a...
[X] Feature request
[X] Documentation issue or request

Hi,

Can this library be used with dotLottie (https://github.com/dotlottie/player-component)  rather than lottie-web?

**Comment by arturovt** [comment]
Hey @Majed93 , thanks for the issue.

Unfortunately, I'm not sure that it's possible. I've never heard of this library, it has only 20 stars and the last commit was in July. It's not reasonable to bring the unknown and unsupported library into codebase and I'm not sure that someone will use.

I'm sure that you can create a simple wrapper for your own project that will perform the assigned tasks.

**Comment by Majed93** [comment]
Ok thanks for the swift reply.

I'm trying to load in a .lottie file instead of a .json, do you know if this library supports it?

**Comment by jjgriff93** [comment]
Was also wondering about this due to the compression benefits. Would this be something this library could support?

**Comment by arturovt** [comment]
The question is, what's required to bring over? I'm not familiar with the 'dot lotite'. If it involves only reusing their player component and creating an Angular wrapper that supports passing bindings, then it may make sense. However, I'm unaware of what someone is expecting from the library.
