### ISSUE TITLE
Clarify the `options` available

### ISSUE THREAD

**Issue by Abhirup-2019** [ngx-lottie/ngx-lottie#97]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: X.Y.Z
- ngx-lottie version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by arturovt** [comment]
Could you elaborate more on the question?

**Comment by arturovt** [comment]
Closing since needs elaboration. Please use the default issue template and don't leave it empty.
