### ISSUE TITLE
How manage responsive behavior with styles property ? 

### ISSUE THREAD

**Issue by gcadoret** [ngx-lottie/ngx-lottie#98]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

All is in the title : How to manage responsive behavior with styles property ? I mean adjust different style for medium screen, large screen, as we can do with the @media css ? 

Thanks

## Environment

<pre><code>
Libs:
- @angular/core version: 11
- ngx-lottie version: latest

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by arturovt** [comment]
Not sure I can answer this question. The CSS part is your responsibility :smile: and you're the only one who knows how to manage it.

**Comment by gcadoret** [comment]
You don't answer my question. How the exsiting feature : "[styles]="styles" manage the  [@Media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/@media)

**Comment by arturovt** [comment]
I'm not answering your question because it's not self-descriptive. You're asking:

>  mean adjust different style for medium screen, large screen, as we can do with the @media css ?

I'm not sure what it means. It's better to elaborate on questions with real-life examples since it's easier to "talk the code".

If you need to update the `[styles]` binding considering the current screen width then you can listen to media changes through JavaScript using `matchMedia()` API and return different `CSSStyleDeclaration` when the media query matches or not, e.g.:
```ts
function matchMedia(query: string) {
  return new Observable<boolean>((observer) => {
    const mql = window.matchMedia(query);
    const onChange = (event: MediaQueryListEvent) =>
      observer.next(event.matches);
    mql.addEventListener('change', onChange);
    observer.next(mql.matches);
    return () => mql.removeEventListener('change', onChange);
  });
}

@Component({
  template: ` <ng-lottie [styles]="styles$ | async"></ng-lottie> `,
})
export class SomeComponent {
  styles$: Observable<Partial<CSSStyleDeclaration>> = matchMedia(
    '(max-width: 600px)'
  ).pipe(
    map((matches) => {
      // If the width is less than 600px then:
      if (matches) {
        return {
          maxWidth: '400px',
        };
      } else {
        return {
          maxWidth: '300px',
        };
      }
    })
  );
}
```

Otherwise you can use the `lottie` directive since it's bound directly to an element which you have an access to:
```ts
<section class="my-animation" lottie ... ></section>

// Somewhere in CSS
@media ... {
  .my-animation { ... }
}
```

**Comment by gcadoret** [comment]
Ok my apologies , indeed, it's possible to handle it with CSSStyleDeclaration

But it's quite complex imho.. 
I found the easy way with a parent div : 
<div class="spinner">
  <ng-lottie [options]="options"  ></ng-lottie>
</div>

and some css like 
.spinner {
  @media (min-width: $medium) {
    padding-top: 10px;
    max-width: 50%;
  }

  @media (max-width: $medium) {
    padding-top: 10px;
    max-width: 50%;
  }
}
thanks you

**Comment by arturovt** [comment]
Well, you can also try to get the deeply nested div inside the `ng-lottie` component, something like this:

```ts
@Component({
  template: `
    <ng-lottie ...></ng-lottie>
  `,
  styles: [
    `
      @media (max-width: 600px) {
        :host ::ng-deep ng-lottie div {
          width: 400px;
        }
      }
    `
  ]
})
```

Also, there is a `containerClass` binding which will be applied to `div`, e.g.:
```html
<ng-lottie containerClass="my-super-cool-class-name"></ng-lottie>
```

So you can use it globally, e.g. in `styles.scss`:
```scss
@media ... {
  .my-super-cool-class-name { ... }
}
```
